server:
  port: 8080
spring:
  application:
    name: java-test-demo
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true


